### ISSUE TITLE
Modularizing OpenSCD

### ISSUE THREAD

**Issue by trusz** [openscd/open-scd#1300]
With this epic we want to modularize OpenSCD for:
- better maintainability and refactorabilty 
- more sharable modules
- easier access management

---

#### Milestone 1: Monorepo:

As a first step we will setup the infrastructure
necessary to have a monorepo that supports multiple packages.
- [ ] Set up npm workspaces: [↗ workspaces | npm Docs](https://docs.npmjs.com/cli/v7/using-npm/workspaces)
- [ ] Adjust release process so that `openscd.github.io` and change logs are not affected

#### Milestone 2: Core:

Publish [↗ openscd/open-scd-core](https://github.com/openscd/open-scd-core) to npm from this repository.

- [ ] Create a `core` package with a copy from [↗ `openscd/open-scd-core`](https://github.com/openscd/open-scd-core)
- [ ] Create release process for `core` to npm
- [ ] Publish the current version of `core` to npm

##### Milestone 3: Trial:

Try out with one of the plugins.

- [ ] Migrate a plugin (tbd.) to the new API

**Comment by Sander3003** [comment]
After every milestone a presentation should be given to the other developers in other to know the current state and give feedback.

**Comment by Sander3003** [comment]
Milestone 1 is done

**Comment by juancho0202** [comment]
please update Milestone 3 @trusz
